export * from './Post/Post';
export * from './Posts/Posts';
export * from './Comments/Comments';
export * from './Comment/Comment';
export * from './Users/Users';
export * from './User/User';
export * from './Details/Details';
export * from './UserDetails/UserDetails';
export * from './Main/Main';